#! /bin/sh

sxhkd & 
xsetroot -cursor_name left_ptr &
picom &
polybar &
feh &

bspc monitor -d I II III IV V 

bspc config border_width         0
bspc config window_gap          10


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color '#222222'
bspc config normal_border_color '#222222'
bspc config focused_border_color '#ffffff'

bspc config honor_size_hints true